### ISSUE TITLE
Override template for admin email order confirmation

### ISSUE THREAD

**Issue by patpluspun** [patpluspun/fmp_au#28]
I’ve had a request from our customer service department to update the automatically-generated email they receive to process online orders.

Presently when an order is placed an email is sent to customer service containing the name, order link, and titles purchased. As all the information they need is not contained in this email the customer service team then has to log into the website to get all the shipping details and so on.

They have requested that all the fields which appear in the ‘Printable Invoice’ be replicated to appear on the automatically-generated email.

Please see attached, these are the fields which are on the ‘Printable Invoice’ which customer service would like to appear on the email order sent to them. Please note, this came from an actual order, so I have replaced some details for privacy.

Could you please let me know if this is possible?

**Comment by janetgatsby** [comment]
go go go

**Comment by patpluspun** [comment]
2 hours for this.

**Comment by janetgatsby** [comment]
ok will add to your tab, want another google wallet payment?

**Comment by patpluspun** [comment]
If you want to do payments that granularly, I'm ok with it.  I am keeping every receipt for record keeping :)

**Comment by janetgatsby** [comment]
Hi Patrick,

I'll send you a 1099 as well. I can also send you an updated spreadsheet on what is paid to-date.

It's up to you when you want the payment, just that the last set of hours from you took a long time to reconcile so I'd thought to try it in shorter bursts. I have hours for you now on closed tickets as follows:

#28 - 2 hours
#44 - 1 hour
#31 - need your hours

**Comment by janetgatsby** [comment]
also ticket #30 I need hours
