### ISSUE TITLE
Add locational free shipping

### ISSUE THREAD

**Issue by patpluspun** [patpluspun/fmp_au#31]
We’d like to offer free shipping on all orders within Australia (delivery to addresses within Australia).

Is it possible to set up a coupon based on delivery location – so it accepts the coupon code if it detects the IP address is within Australia and rejects it if it is outside Australia?

I know the website automatically calculates delivery charges based on location, but I couldn’t see how to set this up in the coupon section.

**Comment by patpluspun** [comment]
I have added this on test.  There doesn't seem to be a way to export Ubercart rules, so I have to recreate this on each environment.  I have attached a screenshot showing how to set up free shipping in AU whenever they want, it's as simple as unchecking the $5.00 option and checking the Free option.

**Comment by janetgatsby** [comment]
@patpluspun looks good on test. Is this checking for an Australian shipping address like we discussed?

**Comment by patpluspun** [comment]
Yes, it uses the exact same rule as the $5 shipping, it just charges $0.00 instead and can be toggled on and off as desired.  I would suggest only using one or the other, however.

**Comment by janetgatsby** [comment]
@patpluspun lock and load. How you doing on #28 ?

**Comment by patpluspun** [comment]
This has made it into production.

**Comment by janetgatsby** [comment]
@patpluspun what's your total hours on this one?

**Comment by patpluspun** [comment]
@janetgatsby 2 hours on this.  I can write a small tutorial if they would like to take over this kind of stuff in the future.
