### ISSUE TITLE
Add Enhanced Ecommerce - Web Tracking (analytics.js)

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#38]
@patpluspun please let me know the LOE to implement this tracking code.

https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce#ecommerce-data

**Comment by janetgatsby** [comment]
@patpluspun did you do this? I am seeing eCommerce tracking in GA since Feb 16, 2105

**Comment by janetgatsby** [comment]
This is AMAZING! Did you know when I was at FMP in 2012 their website revenue was $3K/yr
This 2015 chart is only 8 months! Wish I had tracked this from the beginning!
![screen shot 2015-09-27 at 12 57 00 pm](https://cloud.githubusercontent.com/assets/7650441/10124019/80b01cf4-6517-11e5-8fe4-4156ad04352a.png)

**Comment by patpluspun** [comment]
That is amazing, and has literally made my day.  I will now go out and have sushi to celebrate, then come home and get this release onto production!

**Comment by patpluspun** [comment]
1 hour on this.
