### ISSUE TITLE
Untagging a ‘New Release’ causes ‘infinite loop’ for URL redirects

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#40]
@patpluspun please investigate this latest issue and let give me a diagnosis or fix.

Hi Janet

I’m having ongoing issues with the bug mentioned below. It seems to be that every time a book is untagged as a ‘New Release’ it creates an ‘infinite loop’ for which URL redirects need to be deleted.

At first I only thought this applied to books for which bit.ly URL redirects were assigned to it, but now it seems once a book untagged from being a ‘New Release’ the system is self-creating URL redirects.

Once a book has had the ‘New Releases’ tag removed and I save it, I get the message ‘Oops, looks likethis request tried to create an infinite loop…’ (see screen shot infinite loop). The only way I can remove this message is by following Patrick’s advice below and deleting all URL redirects (see screen shot URL redirects).

It’s strange, as I didn’t create URL redirects for most of the books for which this has occurred today, and both need to be deleted before the message disappeared.

Could this please be investigated and a permanent fix found?    

Thank you

Emily

**Comment by janetgatsby** [comment]
@patpluspun - don't forget this one.

**Comment by patpluspun** [comment]
@janetgatsby I'm updating test right now with this change.  I will let you know when it is ready to review.

**Comment by patpluspun** [comment]
@janetgatsby this is ready to review on http://test.fivemile.com.au

**Comment by janetgatsby** [comment]
@patpluspun 
Confirmed. Tested this on: DreamWorks Dragons Colouring & Puzzle Book which was a New Release. Removed the New Release category, saved. Found book title via search, clicked book, no problems with URL.

Ready for deploy.

**Comment by janetgatsby** [comment]
@patpluspun did this deploy?

**Comment by patpluspun** [comment]
I'm setting up a release for tomorrow right now, and this fix is included.  I'll add whatever else I can get into it as well.

**Comment by patpluspun** [comment]
2 hours on this one

**Comment by janetgatsby** [comment]
@patpluspun just catching up on what is done. did this deploy live?

**Comment by patpluspun** [comment]
This is in the release for today.  I just left a funeral, after I get home
and fix the AC again I'll get it ready to launch.

**Comment by janetgatsby** [comment]
@patpluspun I'm available today if you are to do a release and to catch up on this project.

**Comment by janetgatsby** [comment]
Confirmed on prod. Tested on same book I used for testing on test: DreamWorks Dragons Colouring & Puzzle Book which was a New Release. Removed the New Release category, saved. Found book title via search, clicked book, no problems with URL.
