### ISSUE TITLE
FED - Page number display error on search results

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#41]
@zombiesundays , I think this one is for you my dear.

![example page numbers](https://cloud.githubusercontent.com/assets/7650441/6654250/9d39b47c-ca8d-11e4-8038-1781d347e1a8.jpg)
![page number error_1](https://cloud.githubusercontent.com/assets/7650441/6654252/9d3cd3b4-ca8d-11e4-8bf9-77db21e5d56e.jpg)
![page number error_2](https://cloud.githubusercontent.com/assets/7650441/6654251/9d3cce00-ca8d-11e4-97d5-2d2653ae890b.jpg)

Hi Janet

A new job to start on as soon as you can.

I’ve noticed that the page numbers at the bottom right of the screen for search results are not displaying correctly.

Only the number ‘1’ appears, even when there are multiple pages of search results. Only coloured boxes follow, and it isn’t clear that you need to click on these for further page results.

Examples attached – I searched ‘Shirley Barber’ and there were 2 pages of results. http://www.fivemile.com.au/search/Shirley%20Barber

As you can see, only ‘1’ appears in the page results and it isn’t until you click on the blank box following ‘1’that a second page of results appears.

It is also unusual that so many coloured boxes appear before the ‘2’ – it should just be a single box with ‘1’ to clearly display search result pages.  

Could it please be fixed so that when pages of search results appear there is a single numbered box for each page, and an indication given as to which page you are on (example attached, a change in font or box colour indicating the page you are on. If more pages of results appear than can be shown, a clickable arrow appears to indicate to scroll further page results. Example: bolded font, clickable arrow http://www.shopbop.com/accessories-jewelry-necklaces/br/v=1/2534374302060432.htm?baseIndex=40

Please let me know if you need further clarification.

 

Thank you

**Comment by janetgatsby** [comment]
@zombiesundays, Have you had a chance to look at this issue?

**Comment by janetgatsby** [comment]
@zombiesundays, Could you please look into and fix this issue please?

**Comment by janetgatsby** [comment]
@zombiesundays, this still needs attention please.

**Comment by patpluspun** [comment]
@zombiesundays hit me up on Skype when you can tomorrow, and I'll get everything set up for you.

**Comment by janetgatsby** [comment]
@zombiesundays hello!

**Comment by Svalts** [comment]
Hi @janetgatsby, 

I was able to resolve the issue with the pagination. Let me know what do you think or if you want me to change the styles as well.

http://dev.fivemile.com.au/search/Shirley%20Barber

**Comment by janetgatsby** [comment]
@Svalts this looks great, we can deploy as is. Please let me know your hours for this.
@patpluspun Could we do a deploy today?

**Comment by janetgatsby** [comment]
@Svalts please provide hours for this.  Will go into the deployment.

**Comment by janetgatsby** [comment]
Not on production yet, let's get it in there for today please. Moving to today's milestone.

**Comment by janetgatsby** [comment]
good on test
