### ISSUE TITLE
WEBSITE STOCK ISSUES

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#46]
@patpluspun - please look at this as a priority issue. Thanks - J

From: Renata Watt
Sent: Monday, 20 April 2015 3:15 PM
To: Emily Wan
Cc: Doug Wasley
Subject: WEBSITE STOCK ISSUES

Hi Emily,

An online customer has been able order an item from the website that is showing a negative stock balance on the AS400. They have ordered and paid for an item that is showing -11 in stock. Obviously there is some issue there as I was under the impression when the website was set up that stock showing under 50 or 100 (can’t remember which) would automatically be made unavailable – hence the weekly updates you do with the stock file.

Not sure if this is something that needs to be raised with the website people to check.

I have had other titles over the last few months also come through ( can’t recall which ones but they have all been titles that have been out of stock for a long time).

 

The title in this recent order is ISBN 9781743002605 EXERCISES FOR LETTING GO.

 

It may be just a setting why these titles are slipping through but I know I have checked with Doug before and each time the stock files represent what the AS400 shows that there is no stock but customers are still able to purchase the item??

**Comment by janetgatsby** [comment]
Follow up from Emily:

Hi Janet

 

Please see below from customer service. Could this please be investigated? Please advise of the fix needed.

 

This might tie into the Wooldsheds issue (currently with you) as to why it was showing as OUT OF STOCK when there were 48 copies on the websoh file.

 

I’m not sure what the stock parameters are for a title to appear as OUT OF STOCK – could you please advise once confirmed?

 

Attached is the latest websoh file, should this help.

 

Thanks

Emily

**Comment by patpluspun** [comment]
Could I also get a copy of the last stock update file please?  I will look
into this ASAP.

**Comment by janetgatsby** [comment]
@patpluspun emailed to you as I could not attach here.

**Comment by patpluspun** [comment]
![screen shot 2015-05-21 at 1 05 36 am](https://cloud.githubusercontent.com/assets/3892187/7742583/623d20cc-ff56-11e4-8270-8e889e8fa078.png)
I've attached a screenshot of what the stock for that product looks like.  I couldn't find the ISBN in the stock update file at all, so I'm assuming it went out of stock in a previous file.  It shows as out of stock on production, currently.

I can set a condition to explicitly check for product stock == 0, and not leave it to the ubercart module to ensure that stock is left before letting customers order.  I will update this issue with the PR when it's ready, but I'm afraid I won't get to it tonight.

**Comment by janetgatsby** [comment]
There is no threshold at 50 currently. The book will show in stock until it reaches 0. 
You can set the threshold to any number you want, this will not get overwritten when websoh updates, only the stock field will update.

For this ticket, Patrick to you add a checkbox for "Published, preorder" that when checked instead of "Out of stock" the button will say "October 2015" - which is the date from the Australian Pub Date field.  When the book becomes available in stock, an editor must change from "Published, not available to purchase" to "Published".

**Comment by janetgatsby** [comment]
+1 hour for meeting with me today :)

**Comment by janetgatsby** [comment]
@patpluspun add a checkbox for "Published, preorder"
