### ISSUE TITLE
FED - Text overlapping error on "Buy Now" button

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#47]
Hi Janet

I was just on the website again and noticed the overlapping issue is resolved on the Homepage, but is still occurring on all other website pages. 

When I clicked on the ‘Books’ tab the cart is appearing above the text.

When I clicked on the ‘Ebooks’ tab there is still the overlap.
 
It is happing on all the other webpages too. Please see attached examples.

Could you please have another look at this?
 
Thanks
![books_overlap](https://cloud.githubusercontent.com/assets/7650441/7447860/3dc8dc58-f1d8-11e4-8a0d-de00e1cda1da.jpg)

Em

**Comment by janetgatsby** [comment]
![ebooks_text overlap](https://cloud.githubusercontent.com/assets/7650441/7447909/4db0e66e-f1d9-11e4-93bb-7e4864effa11.jpg)

**Comment by Svalts** [comment]
Seems to be working now on dev. Let me know.

**Comment by janetgatsby** [comment]
Confirmed this is fixed. I also see it already correct on live as well.

**Comment by janetgatsby** [comment]
From Simon: The overlapping cart was removed already (0 mins).
