### ISSUE TITLE
FED - "Apply to Order" button is overlapping the text box

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#48]
I noticed the ‘Apply to Order’ button is overlapping the text box (please see attached). I hit the ‘Refresh’ button but this didn’t move the button into position. Could this please be fixed?
![add to cart](https://cloud.githubusercontent.com/assets/7650441/7447900/118a509e-f1d9-11e4-9721-990f21776d29.jpg)

**Comment by Svalts** [comment]
I was able to change the size and some alignment to the button. Should be working now.

**Comment by janetgatsby** [comment]
Looks good thanks!

**Comment by janetgatsby** [comment]
From Simon: The overlapping was removed also I wasn't able to find any other issue regarding it, Checked and arranged the code as well (30 mins).

**Comment by janetgatsby** [comment]
@Svalts @patpluspun 
This has come back as broken again, overlapping in CHROME only. Please look into it.

**Comment by Svalts** [comment]
@janetgatsby 

In Chrome? I am in Chrome now and I don't see it, did you force refresh your browser?

<img width="1458" alt="screen shot 2015-08-16 at 4 23 14 pm" src="https://cloud.githubusercontent.com/assets/1243419/9295194/2842d16a-4433-11e5-8b23-96267573d9b5.png">

**Comment by janetgatsby** [comment]
I was using a PC laptop that I don't normally use so it shouldn't be cached. W7 on Chrome. I'll check again....

**Comment by janetgatsby** [comment]
@Svalts confirmed it is still happening on production with cleared cache on W7/Chrome v44.0.2403.155

I cleared my cache twice.

**Comment by janetgatsby** [comment]
@Svalts note that on OSX/Chrome v44.0.2403.155 it is not happening. Hope this is a clue.

**Comment by Svalts** [comment]
Which version of Chrome this is happening to you?

**Comment by janetgatsby** [comment]
Chrome v44.0.2403.155 on windows only, not mac

**Comment by Svalts** [comment]
I am seeing it normal in 2 windows computers, @patpluspun you see this bug as well? hmm I will try with different versions of Chrome.

**Comment by janetgatsby** [comment]
@Svalts - I don't know - let's just add more padding and hope that clears it up.

**Comment by patpluspun** [comment]
I see the issue as well, it looks ok with:
```
.page-cart #uc-cart-pane-coupon input#edit-apply {
  margin: 18px 0 0 30px;
}
```

**Comment by Svalts** [comment]
I changed some of the code yesterday tho. However I will add another modification. let me know how it looks now.

**Comment by janetgatsby** [comment]
Hey all, I see this looking good on thttp://test.fivemile.com.au/ can we get it deployed to production today?

**Comment by patpluspun** [comment]
Yes, I'm going to address the urgent issue Emily mentioned as well.  I will
notify when it's available on test.

**Comment by janetgatsby** [comment]
Great, I'm just plowing thru all the emails now and catching up o things

**Comment by janetgatsby** [comment]
looking good on test on chrome
