### ISSUE TITLE
Check into why "Woolsheds" shows as out of stock when there are 48 copies available

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#49]
Related to ticket #46 ?

**Comment by patpluspun** [comment]
![screen shot 2015-05-21 at 1 13 47 am](https://cloud.githubusercontent.com/assets/3892187/7742609/b1cfc626-ff56-11e4-80a0-b57cc42ca085.png)
Here is the current stock level on production for Woolsheds.  The threshold is set to 0, so it shouldn't expire until it hits that.  It currently shows quite a lot of stock.  If the threshold has been adjusted since this ticket was created, that probably resolved the issue.

**Comment by patpluspun** [comment]
Actually, looking into the code there is a condition to set the button to "Out of Stock" when the stock level is under 100, regardless of the threshold set.  I can set this to 1 if desired, and that will ensure products won't go out of stock until they actually hit 0.  I'm fairly sure this was a request from Juliet from way back, but if the use case has changed, I don't mind changing it.

**Comment by janetgatsby** [comment]
@patpluspun What do you mean by "set the button to out of stock"? I don't see an out of stock button but it's funny you mention this because I am reviewing an email from Emily where she is asking the following:
----
A quick question for you.

Is there a setting in the backend to allow a book to be live on the website, but switch of the ability to order it?

I’ve had a request come through to have future titles added to the live website (pub date July onwards), but need to have the ability to purchase them disabled.

I know you can add a book and selected ‘Unpublished’, but this removes it from the website.

As the stock reports feeds through the website, if a title isn’t appearing on the stock list, or stock is at zero, would the book automatically appear as ‘OUT OF STOCK’, and therefore unable to be purchased? If so, I can ask Doug to do this, but it means tampering with stock reports, which isn’t ideal.

If the previously mentioned ability exists, this would be preferable.
 
Please let me know.
----

Patrick, would this work with the 'out of stock' button you're describing?

**Comment by patpluspun** [comment]
Yes.  Simply set the threshold higher than the current stock, and any item should appear as out of stock.  There is no automated way currently to reset it though, so each piece will need to manually be set back to 0 threshold to be able to order again.

If we can come up with a schema in the update .CSV, I could set something up to reset the threshold to zero while it updates from the file.  Perhaps a new field named threshold, with a value of 0?  I could add that today before release.

**Comment by janetgatsby** [comment]
I'll need to check with Emily so don't hold on that for release.
