### ISSUE TITLE
Add Kobo Button, Replace iTunes and Amazon button images

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#56]
1. Add a KOBO button on the book details page. This ‘kobo’ button would be hyperlinked to the eBook version on the kobo website. 

2. Change the iTunes and Amazon button images from FMP styled images to iBooks and Amazon Kindle branded buttons.

3. Please list the buttons in this order:
iBooks
Amazon Kindle 
Kobo

Janet to attach all three buttons PNGs to this ticket today.

**Comment by janetgatsby** [comment]
Attaching images.
![amazon-kindle-100x50](https://cloud.githubusercontent.com/assets/7650441/8268160/d84293ce-1748-11e5-8721-480afc239d2b.png)
![ibooks-100x50](https://cloud.githubusercontent.com/assets/7650441/8268161/d84389dc-1748-11e5-99f8-19b86707a9ca.png)
![kobo-100x50](https://cloud.githubusercontent.com/assets/7650441/8268162/d8441afa-1748-11e5-8001-629c1ff61a47.png)

**Comment by patpluspun** [comment]
This is done and ready to test.
3 hours with theming.

**Comment by janetgatsby** [comment]
@patpluspun can you get the button up a little higher so that the first one is on the same line as the "eBook" header? I see on the current site, Travis is using something in the CSS on the first button

::before

Can you see if adding that will do the trick?

![screen shot 2015-06-20 at 5 51 08 pm](https://cloud.githubusercontent.com/assets/7650441/8269414/07011e16-1775-11e5-8c3f-0da8f2a57a88.png)

**Comment by janetgatsby** [comment]
Tested functionality, works great! If you can get the buttons up a bit higher then it's approved.

**Comment by patpluspun** [comment]
Actually, that ::before was adding the apple icon onto the previous button.  I can certainly slide them up though, one second.

**Comment by janetgatsby** [comment]
It was a wild guess for me that ::before thing.

**Comment by patpluspun** [comment]
Take a look now.

**Comment by janetgatsby** [comment]
Let me give you a new Kindle logo, I hate the box around it.

![amazon-kindle-100x50](https://cloud.githubusercontent.com/assets/7650441/8269476/b9fd208a-1777-11e5-9a78-339ac2104f3a.png)

**Comment by janetgatsby** [comment]
Looks great now, I approve!

**Comment by janetgatsby** [comment]
Both tickets are ready for deployment. Do you want to wait for tomorrow or do them now?

**Comment by patpluspun** [comment]
Ok, I'm feeding my dad at the moment, I'll add the new amazon logo and then we can deploy.

**Comment by patpluspun** [comment]
It is updated with the new logo, I'll begin deployment now.  You can look on test, just make sure to clear your browser history or you'll get the old image.

**Comment by janetgatsby** [comment]
@patpluspun something is weird on production. The KOBO button does work but it's in a strange place on the edit screen. On test it appeared within the ebooks tab, look where it is now:

![screen shot 2015-06-28 at 3 30 53 pm](https://cloud.githubusercontent.com/assets/7650441/8397931/de98e094-1daa-11e5-86b5-5848e66c6b9d.png)

**Comment by janetgatsby** [comment]
FIxed!
