### ISSUE TITLE
FMP site is currently down

### ISSUE THREAD

**Issue by patpluspun** [patpluspun/fmp_au#57]
@janetgatsby I just noticed this, I will address this immediately.  I'll try and get a root cause after it's back up.

**Comment by patpluspun** [comment]
Actually I just cleared caches and everything looks fine. maybe the mysql server got bogged down.  I'll look into this as a separate non-priority issue.

**Comment by janetgatsby** [comment]
I am not having any issues with the site on my end. No down time.

**Comment by janetgatsby** [comment]
Attaching images.
![amazon-kindle-100x50](https://cloud.githubusercontent.com/assets/7650441/8268157/bf35d95e-1748-11e5-8f6f-7fb16791a44e.png)
![ibooks-100x50](https://cloud.githubusercontent.com/assets/7650441/8268159/bf38e4fa-1748-11e5-8727-f069d8affdcf.png)
![kobo-100x50](https://cloud.githubusercontent.com/assets/7650441/8268158/bf388672-1748-11e5-8efe-1c90701fbcfc.png)
