### ISSUE TITLE
BED - Error on 'Garden Friends Buggy Book'

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#60]
http://www.fivemile.com.au/catalog/board-books/garden-friends-buggy-book

Please investigate the error that is happening on this page.

![web error](https://cloud.githubusercontent.com/assets/7650441/8397895/31c2ef0a-1da9-11e5-9913-ac815c8fec29.jpg)

**Comment by janetgatsby** [comment]
@patpluspun let's get this done!

**Comment by patpluspun** [comment]
Ok I've narrowed to down the the function that is misbehaving.  I'll have a fix soon.

**Comment by janetgatsby** [comment]
:) woot
