### ISSUE TITLE
FED - Header image loading issue – Chrome and Internet Explorer

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#61]
please see attached images ‘Web Banner – Chrome’ and ‘Web Banner – IE’

![web banner - ie](https://cloud.githubusercontent.com/assets/7650441/8559090/330d5ca8-24d7-11e5-97c4-ca108ed6d845.jpg)
![web banner - chrome](https://cloud.githubusercontent.com/assets/7650441/8559091/331092ba-24d7-11e5-8053-56ae17740d2e.jpg)

**Comment by patpluspun** [comment]
I've checked in every browser I have on both Windows and Mac, and I cannot reproduce this issue at all.

**Comment by Svalts** [comment]
I was able to reproduce the header issue and made some changes, however it comes randomly it seems but the issue is that the header image is displayed from an HTTPS address, I will try to reproduce this on my PC as well and see if I can recreate it.

**Comment by janetgatsby** [comment]
From Simon: This one I was able to modify the code a bit regarding the header, also it was uploaded using https connection, the cache was cleared. It was tricky to figure it out but I was able to resolve it. (1h 20 mins).

**Comment by janetgatsby** [comment]
@patpluspun this is stil happening on live and it's even more horrible of FF. Did this fix get deployed?

**Comment by Svalts** [comment]
![screen shot 2015-08-02 at 3 21 46 pm](https://cloud.githubusercontent.com/assets/1243419/9027704/a72e774c-392d-11e5-842c-9a1ff5cc81b1.png)


The issue is caused because Drupal is spitting the image using a https instead of http, if you manually change it you will see it fix itself.

**Comment by janetgatsby** [comment]
Closing this ticket and creating a BED ticket. Thank you gentlemen for your research on this.
