### ISSUE TITLE
FED - Internet Explorer - Covers are overlapping each other for some titles in ‘We Also Recommend’ section

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#63]
See attached image.
![2_overlapping covers](https://cloud.githubusercontent.com/assets/7650441/8559182/06555912-24d8-11e5-85e3-be4e2bea05bb.jpg)

**Comment by Svalts** [comment]
Tested on IE 10.

http://dev.fivemile.com.au/catalog/children/wheels-bus

**Comment by janetgatsby** [comment]
Looks good on dev, let's deploy this @patpluspun

**Comment by janetgatsby** [comment]
From Simon: I added some padding just for the images and removed the extra one generated just for Chrome browser. I tested them in all browsers and modify some code regarding that. (20 mins).

**Comment by patpluspun** [comment]
it's going into the next release.
