### ISSUE TITLE
FED - Internet Explorer - The Gift Finder scroll bar is being cut off

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#64]
see attached image

![3_gift finder cut off](https://cloud.githubusercontent.com/assets/7650441/8559200/3b99ce50-24d8-11e5-8e7a-ba12236aea86.jpg)

**Comment by Svalts** [comment]
Fixed it on dev.

**Comment by janetgatsby** [comment]
From Simon: I added more px to the arrows because IE will display 2 instead of 1 like the other browsers, also using nano makes it a little difficult to navigate but I was able to manage (30 mins).

**Comment by janetgatsby** [comment]
Looks good on dev. Let's deploy @patpluspun
