### ISSUE TITLE
BED - The ‘Series’ function isn’t working

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#66]
I noticed that the ‘Series’ function isn’t working – see series ‘Barbie Princess Power’ and ‘Equestria Girls’. Example ISBNs 9781760066840 and 9781760067540

**Comment by janetgatsby** [comment]
@patpluspun would you have time to include this today? If not I'll move it to next milestone.

**Comment by patpluspun** [comment]
I'll fix it.  I'll update this ticket when it's on test.

**Comment by patpluspun** [comment]
This is on test now.

**Comment by patpluspun** [comment]
1 hour.
