### ISSUE TITLE
BED - Header image loading issue

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#72]
The issue is caused because Drupal is displaying the image using a "https" instead of "http", if you manually change it you will see it fix itself.

See ticket #61 for more info.

**Comment by janetgatsby** [comment]
@patpluspun any progress on this?

**Comment by patpluspun** [comment]
Yes, I pushed a fix to test and reloaded the db from prod and hit it a few times.  If everything looks good on test now, I'll go ahead and merge it.

**Comment by janetgatsby** [comment]
@patpluspun Hi, didn't get a text from you last night (also vodka) so here I am today. Please go ahead and merge when you get an opportunity.

**Comment by janetgatsby** [comment]
@patpluspun and let me know your hours.
