### ISSUE TITLE
FED - 'We Also Recommend" covers are unaligned

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#74]
http://www.fivemile.com.au/catalog/new-releases/heartland-celebrating-50-years-australian-conservation-foundation

![ie_we also recommend covers unaligned](https://cloud.githubusercontent.com/assets/7650441/9293952/56e73272-440b-11e5-85eb-94c61face248.jpg)

**Comment by Svalts** [comment]
Sign of the Times book there's extra white space at the top and bottom to make it a square.
It's not a css issue.

<img width="806" alt="2015-08-16" src="https://cloud.githubusercontent.com/assets/1243419/9296779/518477c0-4462-11e5-8090-9126ea072006.png">

**Comment by janetgatsby** [comment]
Thanks @Svalts - let me know how long this took to look into.
