### ISSUE TITLE
BED - Author/Illustrator distinction when creating an Artist Page

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#75]
I’ve noticed that when ‘Illustrator’ is selected when creating an Artist in the section indicating books by this person it says ‘Author’ instead of ‘Illustrator’ – please see attached.

Can this please be updated so that when ‘Illustrator’ is selected for an Artist the wording is updated to ‘Books By This Illustrator’?    
![illustrator wording update](https://cloud.githubusercontent.com/assets/7650441/9293970/f63a4e86-440b-11e5-9ef2-f47491a84ae2.jpg)

**Comment by patpluspun** [comment]
2 hours.

**Comment by janetgatsby** [comment]
Functionality looks good. That H6 style is messed up where is says "Books by this Author" (or Illustrator as the case may be). It's so TINY. It should look more like the "We also recommend" http://www.fivemile.com.au/catalog/adult/long-paddock

Patrick can you fix or do I need to get @Svalts to take a look?

**Comment by janetgatsby** [comment]
Note that the style fix is not a roadblock to deploy this tonight.

**Comment by patpluspun** [comment]
Yes, that was one of the things we reserved for @zombiesundays that didn't get done, it's just a mess in the stylesheet involving those h6's.

**Comment by janetgatsby** [comment]
I'll make a separate ticket.
