### ISSUE TITLE
BED - Changes to eBooks Landing Page

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#76]
Please remove price from the eBooks landing page 
 – no price to be displayed
 – no "add to cart" to be displayed

http://www.fivemile.com.au/catalog/ebooks-0

NOTE: this is for the titles as appearing in the EBOOK LANDING PAGE ONLY, no changes to the print version listing pages (e.g. listing as the book appears in other sections of the website). 

![ebooks landing page - no prices](https://cloud.githubusercontent.com/assets/7650441/9293984/85d1fe90-440c-11e5-841c-2407ece087d1.jpg)

**Comment by janetgatsby** [comment]
@patpluspun I'm guessing you did work on this page as I'm seeing the print price and 'buy now' button is gone. 

Functionality wise - OK. However I am seeing 3 titles across instead of 4 on all browsers.

**Comment by patpluspun** [comment]
Yes, I'm not sure if it needs styling fixes or changes on my end.  I'll spend a little time to figure it out, unless @Svalts wants to take it over.

**Comment by janetgatsby** [comment]
@patpluspun see if you can fix it so this can go tonight. It was one of Emily's priorities.

**Comment by patpluspun** [comment]
2 hours, this was mostly my end, had a few more things to fix.

**Comment by janetgatsby** [comment]
Looks good on test, even has the corrected # of books per row
