### ISSUE TITLE
BED - Minimum spend free shipping

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#81]
Hi Janet and Patrick
We had on our forthcoming task list adding a minimum spend to free shipping.
I have been advised that we are doing a free shipping (minimum spend required) for October – December.
Is it possible to have this functionality up and running before then? The functionality would allow me to select the free shipping option (exists), and then enter the minimum spend amount required for the free shipping to action.
Functionality should remain that free shipping with no minimum spend is still an option, but if an amount is entered into the minimum spend box this triggers the appropriate calculation at the checkout.    
Is this possible? Please advise.
Many thanks

----------
Hi Emily,
Just a few questions:

Where would you be selecting this option?  It sounds like it should just go into the general settings, which would override the shipping once a certain purchase threshold is reached.  Will this work internationally or only for certain countries?

Thanks,
Patrick

----------

Hi Patrick

The general settings sounds ok– maybe alongside where you tick the ‘Free Shipping’ box?

At this point it would be for Australian customers only.

Thanks
Em

**Comment by janetgatsby** [comment]
@patpluspun is this one for tonight? This is the email I say Emily marked as "Urgent".

**Comment by patpluspun** [comment]
I don't think so, this isn't achievable through coupons like I thought it would be.  We can do an out of band release next weekend for it, and any problems can be reported in time for the in band release in two weeks.

**Comment by janetgatsby** [comment]
Allright, let's plan for that. I work every weekend anyway :)

**Comment by patpluspun** [comment]
6 hours on this, I explored many avenues to get the right functionality here.
