### ISSUE TITLE
BED - Report showing ISBN # that were in the STWEB.xlsxx but were ignored because there were no matches on the website

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#82]
Re ticket #65, you said you could generate this report.

**Comment by patpluspun** [comment]
Github does not allow .txt attachments, so I have emailed Emily a copy and cc'ed you on it, @janetgatsby

**Comment by patpluspun** [comment]
It took about 2 minutes to create a report from the output, we can roll it into another ticket.

**Comment by janetgatsby** [comment]
roger that. just add some time to another ticket.
