### ISSUE TITLE
BED - Add "Photographer" option when creating an Artist Page

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#83]
Relates to ticket #75 
![add to create artist - role photographer](https://cloud.githubusercontent.com/assets/7650441/9837935/9c741706-5a1d-11e5-8f92-2d010631584d.jpg)
 

Hi Janet and Patrick

Can you please log the following ticket as an immediate job:

Create the option of ‘Photographer’ in Create Artist

At present only the two options are available:
-          Author
-          Illustrator

Can the third option of Photographer please be added.

Attached image for your reference.

**Comment by patpluspun** [comment]
1 hour.

**Comment by janetgatsby** [comment]
Approved, looking good on Dev.
