### ISSUE TITLE
Scoping - Adding BPAY + PayPal functionality to checkout/payment options

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#85]
https://www.paypal.com/au/home

http://www.bpay.com.au/

**Comment by patpluspun** [comment]
Paypal is fairly easy, there's already a module for it, I just have to configure it.

Bpay is a different beast entirely, it looks more like a recurring billing thing from the outside.  If I can find a prebuilt widget they provide it'll definitely help, but this could be a huge task if I have to build it from scratch.  But then there would be a Bpay drupal module in the world.

**Comment by janetgatsby** [comment]
Let's split these into two implementation tasks. Let me know how many hours you spent on this research item.
