### ISSUE TITLE
BED - Left Nav eBooks still shows price and Buy It Now button

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#87]
@patpluspun the URL from the left nav:
http://test.fivemile.com.au/catalog/ebooks-0

Does not show the updated ebooks landing page: http://test.fivemile.com.au/ebooks

Can we redirect it?

**Comment by janetgatsby** [comment]
Sorry, one other thing I forgot to mention, using your direct link to the eBooks page (http://www.fivemile.com.au/ebooks) I noticed that ‘Featured Books’ aren’t appearing.

See difference here using my link from the Hompeage and navigating to ‘eBooks’ tab: http://www.fivemile.com.au/catalog/ebooks-0, ‘Featured Books’ box appears.

**Comment by patpluspun** [comment]
I added a redirect on www manually, and the featured ebooks will be fixed with the push.

**Comment by patpluspun** [comment]
1 hour to replace featured block and add redirect, very minor styling.

**Comment by patpluspun** [comment]
1 hour on this.
