### ISSUE TITLE
BED - Add Field for Photographer Credit on Book Detail Page

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#91]
Can functionality please be added so that when a Photographer is added their name appears as does with Authors and Illustrators? See attached an example URL, which lists both the author and Illustrator and the update noted in the image below.

Example: http://www.fivemile.com.au/catalog/new-releases/christmas-grandmas-beach-house

![photographer name added to book title page](https://cloud.githubusercontent.com/assets/7650441/10123426/16beab04-6507-11e5-92dd-9430ba979ae3.jpg)

**Comment by janetgatsby** [comment]
Closing, duplicate of #83

**Comment by patpluspun** [comment]
2 hours on this.
