### ISSUE TITLE
BED - Install Google Tag Manager

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#92]
Copy the code below and paste it onto every page of your website. Place it immediately after the opening <body> tag.
```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PQHFZ5"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PQHFZ5');</script>
<!-- End Google Tag Manager -->
```

**Comment by patpluspun** [comment]
Did you forget to paste the code, @janetgatsby ?

**Comment by janetgatsby** [comment]
oh crap, I thought I did!


<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PQHFZ5"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PQHFZ5');</script>

**Comment by janetgatsby** [comment]
OH I DID!! But, Git is stripping it out. I'll email it to you.

**Comment by patpluspun** [comment]
For future reference, code can be pasted in by using three backticks:

```
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PQHFZ5"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PQHFZ5');</script>
<!-- End Google Tag Manager -->
```

**Comment by patpluspun** [comment]
1 hour
